// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLruHggwUmC9KM15nHY_jBFRctZ-N9Huk',
    appId: '1:562917742570:web:344fdac3576ca285a88493',
    messagingSenderId: '562917742570',
    projectId: 'chat-app-d178d',
    authDomain: 'chat-app-d178d.firebaseapp.com',
    storageBucket: 'chat-app-d178d.appspot.com',
    measurementId: 'G-KG92X3NBMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdJ87v0ShD-urr6Te4NaxGyC8CtQnFrh0',
    appId: '1:562917742570:android:7ae514fd63e8cdeaa88493',
    messagingSenderId: '562917742570',
    projectId: 'chat-app-d178d',
    storageBucket: 'chat-app-d178d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIVRY6pDca8BWHy_-HgVX1CqUxUAYeGGk',
    appId: '1:562917742570:ios:a49f170c341900eda88493',
    messagingSenderId: '562917742570',
    projectId: 'chat-app-d178d',
    storageBucket: 'chat-app-d178d.appspot.com',
    iosBundleId: 'com.example.whatsApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIVRY6pDca8BWHy_-HgVX1CqUxUAYeGGk',
    appId: '1:562917742570:ios:a49f170c341900eda88493',
    messagingSenderId: '562917742570',
    projectId: 'chat-app-d178d',
    storageBucket: 'chat-app-d178d.appspot.com',
    iosBundleId: 'com.example.whatsApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLruHggwUmC9KM15nHY_jBFRctZ-N9Huk',
    appId: '1:562917742570:web:571b905928097b32a88493',
    messagingSenderId: '562917742570',
    projectId: 'chat-app-d178d',
    authDomain: 'chat-app-d178d.firebaseapp.com',
    storageBucket: 'chat-app-d178d.appspot.com',
    measurementId: 'G-CW018GCZVF',
  );
}
